#!/usr/bin/env python3
"""
recon-arsenal :: utils/output.py
Shared output formatters, report generator, and color helpers.
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich import box

console = Console()

SEV_COLOR = {
    "CRITICAL": "bold red",
    "HIGH":     "orange3",
    "MEDIUM":   "yellow",
    "LOW":      "green",
    "INFO":     "blue",
    "NONE":     "dim",
}

SEV_ORDER = {"CRITICAL": 5, "HIGH": 4, "MEDIUM": 3, "LOW": 2, "INFO": 1}


def sev_color(severity: str) -> str:
    return SEV_COLOR.get(severity.upper(), "white")


def print_banner(tool_name: str, version: str = "1.0"):
    width = 50
    border = "-" * width
    console.print(f"[cyan]+{border}+[/cyan]")
    console.print(f"[cyan]¦[/cyan]{'recon-arsenal :: ' + tool_name + ' v' + version:^{width}}[cyan]¦[/cyan]")
    console.print(f"[cyan]¦[/cyan]{'Authorized Security Testing Only':^{width}}[cyan]¦[/cyan]")
    console.print(f"[cyan]+{border}+[/cyan]")


def print_finding(severity: str, title: str, detail: str = "", url: str = ""):
    c = sev_color(severity)
    parts = [f"[{c}][{severity}][/{c}] [bold]{title}[/bold]"]
    if url:
        parts.append(f"  [dim]{url}[/dim]")
    if detail:
        parts.append(f"  {detail}")
    console.print("\n".join(parts))


def findings_table(findings: list[dict], title: str = "Findings") -> Table:
    t = Table(title=title, box=box.ROUNDED, show_lines=True)
    t.add_column("Severity", width=10)
    t.add_column("Name", width=30)
    t.add_column("URL / Target")
    t.add_column("Detail")

    for f in sorted(findings, key=lambda x: SEV_ORDER.get(x.get("severity","INFO").upper(), 0), reverse=True):
        sev = f.get("severity","INFO").upper()
        c = sev_color(sev)
        t.add_row(
            f"[{c}]{sev}[/{c}]",
            f.get("name", f.get("vuln_type", "")),
            f.get("url", f.get("matched_at", "")),
            f.get("evidence", f.get("detail", ""))[:80],
        )
    return t


def save_json(data: Any, path: str):
    Path(path).write_text(json.dumps(data, indent=2, default=str))
    console.print(f"[green]? Saved ? {path}[/green]")


def save_txt(lines: list[str], path: str):
    Path(path).write_text("\n".join(lines))
    console.print(f"[green]? Saved ? {path}[/green]")


def generate_report(tool: str, target: str, findings: list[dict], output_path: str):
    """Generate a Markdown report."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %Human:%M UTC")
    counts = {}
    for f in findings:
        sev = f.get("severity", "INFO").upper()
        counts[sev] = counts.get(sev, 0) + 1

    lines = [
        f"# Security Assessment Report",
        f"",
        f"**Tool:** recon-arsenal :: {tool}  ",
        f"**Target:** {target}  ",
        f"**Date:** {timestamp}  ",
        f"**Total Findings:** {len(findings)}  ",
        f"",
        f"## Summary",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
    ]
    for sev in ["CRITICAL","HIGH","MEDIUM","LOW","INFO"]:
        if sev in counts:
            lines.append(f"| {sev} | {counts[sev]} |")

    lines += ["", "## Findings", ""]
    for f in sorted(findings, key=lambda x: SEV_ORDER.get(x.get("severity","INFO").upper(),0), reverse=True):
        lines += [
            f"### [{f.get('severity','INFO').upper()}] {f.get('name', f.get('vuln_type',''))}",
            f"",
            f"**URL:** `{f.get('url', f.get('matched_at',''))}`  ",
            f"**Evidence:**",
            f"```",
            f"{f.get('evidence', f.get('detail',''))[:500]}",
            f"```",
            f"",
        ]

    lines += [
        "---",
        "*Generated by recon-arsenal. For authorized use only.*",
    ]

    Path(output_path).write_text("\n".join(lines))
    console.print(f"[green]? Markdown report ? {output_path}[/green]")